version: '3.1'

volumes:
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./docker/config/mongo:/data/db

  promtail:
    image: grafana/promtail
    volumes:
      - ./docker/config/promtail:/etc/promtail
    command:
      - '-config.file=/etc/promtail/promtail.yml'
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:main-ubuntu
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    volumes:
      - ./docker/config/loki:/etc/loki